pipeline {
    agent any

    tools {
        maven 'Maven3'
        jdk   'JDK21'
    }

    environment {
        DOCKER_IMAGE  = 'cicd-demo'
        DOCKER_TAG    = "${BUILD_NUMBER}"
        TOMCAT_WEBAPPS = 'apache-tomcat-9.0.117/webapps'
    }

    stages {

        stage('Source') {
            steps {
                echo '--- Pulling source from GitHub ---'
                checkout scm
            }
        }

        stage('Build') {
            steps {
                echo '--- Building WAR with Maven ---'
                dir('cicd-demo') {
                    sh 'mvn clean package -DskipTests'
                }
            }
            post {
                success {
                    archiveArtifacts artifacts: 'cicd-demo/target/*.war'
                    echo 'WAR built successfully!'
                }
            }
        }

        stage('Test') {
            steps {
                echo '--- Running unit tests ---'
                dir('cicd-demo') {
                    sh 'mvn test'
                }    
            }
        }

        stage('Dockerize') {
    steps {
        sh """
            docker build -t ${DOCKER_IMAGE}:${DOCKER_TAG} -f cicd-demo/Dockerfile cicd-demo
        """
    }
}

        stage('Deploy') {
            steps {
                echo '--- Deploying to Tomcat on EC2 ---'
                
            sh """
                docker build -t ${DOCKER_IMAGE}:${DOCKER_TAG} .
                docker tag ${DOCKER_IMAGE}:${DOCKER_TAG} ${DOCKER_IMAGE}:latest
            """
        
            }
        }
    }

    post {
        success { echo '✅ Pipeline SUCCESS — App is live!' }
        failure { echo '❌ Pipeline FAILED — check logs.' }
    }
}
