pipeline {
    agent any

    tools {
        maven 'Maven3'
        jdk   'JDK21'
    }

    environment {
        DOCKER_IMAGE  = 'cicd-demo'
        DOCKER_TAG    = "${BUILD_NUMBER}"
        TOMCAT_WEBAPPS = '/root/apache-tomcat-9.0.117/webapps'
    }

    stages {

        stage('Source') {
            steps {
                echo '--- Pulling source from GitHub ---'
                checkout scm
            }
        }

        stage('Build') {
            steps {
                echo '--- Building WAR with Maven ---'
                dir('cicd-demo') {
                    sh 'mvn clean package -DskipTests'
                }
            }
            post {
                success {
                    archiveArtifacts artifacts: 'cicd-demo/target/*.war'
                    echo 'WAR built successfully!'
                }
            }
        }

        stage('Test') {
            steps {
                echo '--- Running unit tests ---'
                dir('cicd-demo') {
                    sh 'mvn test'
                }    
            }
        }

        stage('Dockerize') {
    steps {
        sh """
            docker build -t ${DOCKER_IMAGE}:${DOCKER_TAG} -f cicd-demo/Dockerfile cicd-demo
        """
    }
}

        stage('Deploy') {
    steps {
        echo '--- Deploying to Tomcat ---'
        sh """
            sudo cp cicd-demo/target/cicd-demo.war ${TOMCAT_WEBAPPS}/
            sudo chown jenkins:jenkins ${TOMCAT_WEBAPPS}/cicd-demo.war
            sudo rm -rf ${TOMCAT_WEBAPPS}/cicd-demo
            sudo /root/apache-tomcat-9.0.117/bin/shutdown.sh || true
            sleep 3
            sudo /root/apache-tomcat-9.0.117/bin/startup.sh
        """
    }
}

        stage('Run Docker') {
    steps {
        echo '--- Running Docker Container ---'
        sh """
            docker rm -f cicd-container || true

            docker run -d -p 8081:8080 \
                --name cicd-container \
                ${DOCKER_IMAGE}:${DOCKER_TAG}
        """
    }
}
    }

    post {
        success { echo '✅ Pipeline SUCCESS — App is live!' }
        failure { echo '❌ Pipeline FAILED — check logs.' }
    }
}
